name: payload_dumper

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://ota-cdn.lenovo.com/firmware/2024828185240998-6800.zip
  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: '3.14.0-alpha.0' 
    - name: Initialization environment 
      run: |
        cd ~
        pip install bsdiff4
        pip install protobuf
        pip install six
        pip install brotli

    - name: Clean Up Disk Space
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        
    - name: Clone the tools source code
      run: |
       cd ~
       mkdir payload_dumper
       ls
       cd payload_dumper
       wget -O payload_dumper.py https://github.com/vm03/payload_dumper/raw/refs/heads/master/payload_dumper.py
       wget -O update_metadata_pb2.py https://github.com/vm03/payload_dumper/raw/refs/heads/master/update_metadata_pb2.py
       
  
    - name: Download the ROM
      run: |
       cd ~
       wget -O rom.zip $ROM_URL
   
    - name: unzip the ROM
      run: |
       cd ~
       unzip rom.zip -d payload_dumper
    
    - name: extract the payload.bin
      run: |
       cd ~
       cd payload_dumper
       python payload_dumper.py payload.bin
   

    
    - name: Upload the bootimg to WeTransfer
      run: |
        cd ~
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ~/payload_dumper/output/boot.img
